/*
 * WaitFrame.java
 *
 * Created on June 11, 2008, 12:23 AM
 */

package minoe;

/**
 *
 * @author  Dan Spiteri
 */
public class WaitFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form WaitFrame */
    public WaitFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(WaitFrame.class, "WaitFrame.jLabel1.text_1")); // NOI18N
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
