/*
 * Welcome.java
 *
 * Created on January 22, 2008, 10:44 PM
 */

package minoe;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import org.openide.util.Exceptions;


/**
 *
 * @author  Dan Spiteri
 */
public class Welcome extends javax.swing.JInternalFrame {
    CustomDesktopPane owner;
    /** Creates new form Welcome */
    public Welcome() {
        initComponents();
        
        this.owner = (CustomDesktopPane) getParent();

        setCenter();
    }

    public void setCenter(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getWidth();
        int height = this.getHeight();
        // attempt to center the screen on the page
        this.setLocation((screenSize.width - width) / 2, (screenSize.height - height) / 2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        gapAnalysisButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        visualAnalysisButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Welcome to MINOE");
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 250));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("MINOE");
        jLabel1.setIconTextGap(0);
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 50));

        jSeparator1.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(575, 5));
        jPanel6.add(jSeparator1);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setText("Please make a choice from the options below or the menu up top.");
        jPanel6.add(jLabel5);

        jSeparator2.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(575, 5));
        jPanel6.add(jSeparator2);

        getContentPane().add(jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 45));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        gapAnalysisButton.setFont(new java.awt.Font("Arial", 0, 12));
        gapAnalysisButton.setText("Gap Analysis");
        gapAnalysisButton.setMaximumSize(new java.awt.Dimension(175, 25));
        gapAnalysisButton.setMinimumSize(new java.awt.Dimension(175, 25));
        gapAnalysisButton.setPreferredSize(new java.awt.Dimension(175, 25));
        gapAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gapAnalysisButtonActionPerformed(evt);
            }
        });
        jPanel3.add(gapAnalysisButton);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setText(" Model ecosystem elements across documents.");
        jLabel3.setMaximumSize(new java.awt.Dimension(1000, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 15));
        jPanel3.add(jLabel3);

        jPanel2.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(650, 25));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 35));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        visualAnalysisButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        visualAnalysisButton.setText("Visualization Module");
        visualAnalysisButton.setMaximumSize(new java.awt.Dimension(175, 25));
        visualAnalysisButton.setMinimumSize(new java.awt.Dimension(175, 25));
        visualAnalysisButton.setPreferredSize(new java.awt.Dimension(175, 25));
        visualAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualAnalysisButtonActionPerformed(evt);
            }
        });
        jPanel5.add(visualAnalysisButton);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(" Interactive graphical analysis.");
        jPanel5.add(jLabel2);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gapAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gapAnalysisButtonActionPerformed
        try {
            GapsWizardChooser gapsWizardChooser = new GapsWizardChooser(this.owner);
            gapsWizardChooser.setVisible(true);
            this.owner.add(gapsWizardChooser);
            gapsWizardChooser.setSelected(true);
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
        this.dispose();
}//GEN-LAST:event_gapAnalysisButtonActionPerformed

    private void visualAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt){
        try {
            DrawFrame drawFrame = new DrawFrame();
            drawFrame.setParentOwner(this.owner);
            drawFrame.setVisible(true);
            this.owner.add(drawFrame);
            drawFrame.pack();
            drawFrame.setMaximum(true); // Default to max screen size.
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);                                              
        }
             
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gapAnalysisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton visualAnalysisButton;
    // End of variables declaration//GEN-END:variables
    
    public void setOwner (CustomDesktopPane owner){
        this.owner = owner;
    }
}
